### ISSUE TITLE
[question] Definition of non primitive types

### ISSUE THREAD

**Issue by bokay** [witchcrafters/algae#58]
Hello there!

I have started using the library to define types and was wondering what is the correct way to deal with non primitive Erlang types that does not implement a `new/0` function (eg: `Date.t()` from Elixir, or from other libraries like `Decimal.t()`)

For example with Decimal.t, I get this error: 
```
defmodule SomeType do
  import Algae
  defdata do
    value :: Decimal.t()
  end
end
```

```
** (UndefinedFunctionError) function Decimal.new/0 is undefined or private. Did you mean one of:

      * new/1
      * new/3
```
I have used `any()` as a workaround, but I would love to know what is the better alternative.

Cheers and thanks!

**Comment by icidasset** [comment]
Hi @bokay  👋 

I've got two solutions to this:
1. Make a new module with just a `new/0` method and a `@type t` (this would only be used for the algae type definition)
2. Use https://github.com/andrewvy/method_missing and use this module instead everywhere (see example below)

```elixir
defmodule MyApp.DateTime do
  use MethodMissing

  @type t :: Elixir.DateTime.t

  @spec new :: t
  def new, do: Elixir.DateTime.utc_now()

  # Redirect other method calls to the Elixir.DateTime module.
  def method_missing(func, args), do: apply(Elixir.DateTime, func, args)
end
```

**Comment by bokay** [comment]
Hello @icidasset :wave: 

The method missing pattern feels very ruby-esque but will do the job indeed as long as there's not too many Elixir types to wrap (feeling lazy).

Thank you very much for your reply!
